# Generated by Django 6.0.5 on 2026-05-09 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gamenets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('station_type', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('free', 'Free'), ('playing', 'Playing'), ('offline', 'Offline')], default='free', max_length=20)),
                ('gamenet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamenets.gamenet')),
            ],
        ),
        migrations.CreateModel(
            name='StationTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price_per_hour', models.PositiveIntegerField()),
                ('is_vip', models.BooleanField(default=False)),
                ('gamenet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamenets.gamenet')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.station')),
            ],
        ),
        migrations.CreateModel(
            name='VipService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('gamenet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamenets.gamenet')),
            ],
        ),
    ]
